name: energise_pro_testing
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  flutter_map: ^6.1.0
  flutter_svg: ^2.0.10+1
  get_ip_address: ^0.0.6
  http: ^1.2.0
  latlong2: ^0.9.1
  share_plus: ^5.0.0
  webview_flutter: ^4.5.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
